[project]
name = "eyenerf"
version = "1.0"

dependencies=[
    "kornia",
    "nerfstudio"
]

[tool.setuptools.packages.find]
include = ["eyenerf*"]

[project.entry-points.'nerfstudio.method_configs']
eyenerf = 'eyenerf.eyenerf_config:eyenerf_method'
